### ISSUE TITLE
Get Jupyter running at a SLURM site

### ISSUE THREAD

**Issue by ericfranz** [OSC/bc_osc_jupyter#11]
On a branch, modify the files necessary to get Jupyter running at a SLURM site. We can use an ssh tunnel to connect and if necessary install Jupyter in our home directory.

Having this working, modified version at another site will help us understand what parts are Torque and OSC specific and make it easier to discuss generalizing Jupyter or documenting how to fork and modify Jupyter to run elsewhere.

**Comment by ericfranz** [comment]
Perhaps we should wait on this until we implement https://github.com/OSC/ood-dashboard/issues/179?

**Comment by nickjer** [comment]
Moved to https://github.com/OSC/bc_example_jupyter/
