### ISSUE TITLE
Enable users to bring their own conda env

### ISSUE THREAD

**Issue by johrstrom** [OSC/bc_osc_jupyter#62]
We have a user that wants to launch Jupyter interactively and connect to it because they have their own conda environment  and wish to use _it_ instead of pip installed packages.

I'm wondering if we could just add a checkbox to launch under their own conda environment instead of under our modules and so on.

**Comment by johrstrom** [comment]
We should let the user in TASK0037247 know when this becomes available.

**Comment by ZQyou** [comment]
We already have the solution here: https://www.osc.edu/resources/getting_started/howto/howto_use_a_condavirtual_environment_with_jupyter

To manage packages through Jupyter notebook, user must run

**Comment by johrstrom** [comment]
Thanks ZQ!
