### ISSUE TITLE
Add support for Python 2

### ISSUE THREAD

**Issue by nickjer** [OSC/bc_osc_jupyter#7]
A user should be able to choose to launch Jupyter with either Python 2 or Python 3.

```bash
module load python/2.7
```

Requested in SN Ticket: [INC0315978](https://oarnet.service-now.com/nav_to.do?uri=incident.do?sys_id=d6df3ee613e67600804831f18144b0ae)

**Comment by nickjer** [comment]
Pinged OSC Sci Apps about their thoughts on adding a Python 2 kernel to our current implementation of Jupyter that uses Python 3.

SN Ticket: [INC0316002](https://oarnet.service-now.com/nav_to.do?uri=incident.do?sys_id=9704bafa136e7600804831f18144b00b)

**Comment by basilgohar** [comment]
Just to follow-up a bit on this, based on Kevin's comments in SN I've added this to our Ingest list in Asana.

**Comment by nickjer** [comment]
Turns out there is a method that user's themselves can do to add Python 2 to their Jupyter Notebook. From Heechang:

>I confirm that we can add any python kernel to Jupyter by local installation.
>
>After we load the python, we can create a local python version by
>
>```sh
>conda create -n {local python name} python={version} anaconda
>```
>I did for `mypython3` and `py2.7`, and both are appeared on Jupyter.
>I attached a screen shot of it.

![image](https://user-images.githubusercontent.com/4260509/27046609-18f1f4d2-4f73-11e7-9eda-11e3cd862282.png)

So I am marking this done.
