### ISSUE TITLE
Investigate using Jupyter Authentication Token with GET instead of POST request

### ISSUE THREAD

**Issue by ericfranz** [OSC/bc_osc_jupyter#8]
https://blog.jupyter.org/2016/12/21/jupyter-notebook-4-3-1/

>We have just released Jupyter Notebook 4.3.0 and 4.3.1 with some important security fixes.
>
>## 4.3.0: Token authentication
> The biggest change in 4.3 is the addition of token-based authentication, which is **enabled by default.**

This would allow us to re-enable xsrf (and csrf) protection in Jupyter because we can avoid using a POST request in a web form from the vncsim connection tab when launching Jupyter and still get single sign on.

**Comment by nickjer** [comment]
From the documentation in regards to token authentication:

![image](https://cloud.githubusercontent.com/assets/4260509/26278282/89cdee02-3d64-11e7-8440-68c462c8f532.png)

- the first one can cause issues if the proxy uses basic auth for user authentication
- the second one will leave the tokens exposed in the proxy logs
- the last one leads us back to how we currently do things
